CREATE TABLE IF NOT EXISTS produtos(

    ID INT  AUTO,
    DESCRICAO VARCHAR(50) NOT NULL,
    VALOR FLOAT() NOT NULL,
    QUANTIDADE_ESTOQUE INT NOT NULL,
    PRIMARY KEY ('ID')
);

CREATE TABLE IF NOT EXISTS funcionarios(
    ID_FUNCIONARIO INT AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    CPF_CNPJ CHAR(14) NOT NULL UNIQUE,
    SENHA VARCHAR(16) NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL,
    CARGO ENUM('GERENTE', 'ADMINISTRADOR') NOT NULL,
    PRIMARY KEY ('ID_FUNCIONARIO')
);

CREATE TABLE IF NOT EXISTS pedidos(
    ID_PEDIDO INT AUTO_INCREMENT,
    FORMA_PAGAMENTO ENUM('CARTAO DE CREDITO', 'CARTAO DE DEBITO', 'BOLETO', 'PIX') NOT NULL,
    STATUS_PEDIDO ENUM('AGUARDANDO CONFIRMACAO DE PAGAMENTO', 'EM SEPARACAO', 'ENVIADO','ENTREGUE') NOT NULL,
    NOME_CLIENTE VARCHAR(50) NOT NULL,
    TELEFONE_CLIENTE CHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS clientes(
    ID_CLIENTE INT AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    CPF_CNPJ CHAR(14) NOT NULL,
    RG VARCHAR(8) NOT NULL,
    SEXO ENUM('MASCULINO', 'FEMININO') NOT NULL,
    SENHA VARCHAR(16) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TELEFONE  VARCHAR(11) NOT NULL
    PRIMARY KEY ('ID_CLIENTE')
);

CREATE TABLE IF NOT EXISTS cupons(
    ID_CUPOM INT AUTO_INCREMENT,
    NOME VARCHAR(15) NOT NULL UNIQUE,
    VALOR_DESCONTO FLOAT  NOT NULL
    PRIMARY KEY ('ID_CUPOM')
);

