CREATE TABLE IF NOT EXISTS produtos(
    ID INT  AUTO_INCREMENT,
    DESCRICAO CHAR(50) NOT NULL,
    VALOR FLOAT NOT NULL,
    QUANTIDADE_ESTOQUE INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS funcionarios(
    ID_FUNCIONARIO INT AUTO_INCREMENT,
    NOME CHAR(50) NOT NULL,
    EMAIL CHAR(50) NOT NULL UNIQUE,
    CPF_CNPJ CHAR(14) NOT NULL UNIQUE,
    SENHA CHAR(16) NOT NULL,
    TELEFONE CHAR(11) NOT NULL,
    CARGO ENUM('GERENTE', 'ADMINISTRADOR') NOT NULL,
    PRIMARY KEY (ID_FUNCIONARIO)
);

CREATE TABLE IF NOT EXISTS pedidos(
    ID_PEDIDO INT AUTO_INCREMENT,
    FORMA_PAGAMENTO ENUM('CARTAO DE CREDITO', 'CARTAO DE DEBITO', 'BOLETO', 'PIX') NOT NULL,
    STATUS_PEDIDO ENUM('AGUARDANDO CONFIRMACAO DE PAGAMENTO', 'EM SEPARACAO', 'ENVIADO','ENTREGUE') NOT NULL,
    NOME_CLIENTE CHAR(50) NOT NULL,
    TELEFONE_CLIENTE CHAR(11) NOT NULL,
    PRIMARY KEY (ID_PEDIDO)
);

CREATE TABLE IF NOT EXISTS clientes(
    ID_CLIENTE INT AUTO_INCREMENT,
    NOME CHAR(50) NOT NULL,
    CPF_CNPJ CHAR(14) NOT NULL,
    RG CHAR(8) NOT NULL,
    SEXO ENUM('MASCULINO', 'FEMININO') NOT NULL,
    SENHA CHAR(16) NOT NULL,
    EMAIL CHAR(50) NOT NULL,
    TELEFONE CHAR(11) NOT NULL,
    PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE IF NOT EXISTS cupons(
    ID_CUPOM INT AUTO_INCREMENT,
    NOME CHAR(15) NOT NULL UNIQUE,
    VALOR_DESCONTO FLOAT  NOT NULL,
    PRIMARY KEY (ID_CUPOM)
);

